sonar.organization=ammar-yasir
sonar.projectKey=ammar-yasir_multilines-technical-task
sonar.projectName=multilines-technical-task
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Source
sonar.sources=src
sonar.tests=src

# Include test files
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx

# Exclude
sonar.exclusions=node_modules/**,.next/**,dist/**,build/**,coverage/**

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# TS config (if using TS)
sonar.typescript.tsconfigPath=tsconfig.json